spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelreservation
    password: taskmastarh
    username: taskmastarh
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.show_syntax: true
  security:
    user:
      name: me
      password: 12345
server:
  error:
    path: /error
    whitelabel.enable: false